events_schema = {
    "time": "timestamp",
    "start_time": "timestamp",
    "end_time": "timestamp",
    "shift_id": "int",
    "shift_start": "timestamp",
    "shift_end": "timestamp",
    "production_date": "timestamp",
    "production_target": "float",
    "produced": "int",
    "machine_name": "string",
    "scrapped": "int",
    "event_duration": "int",
    "status_code": "int",
    "part_number": "string",
    "ideal_cycle_time": "float",
    "factory_order": "string",
    "id": "int",
    "seconds_per_part": "float",
    "multiplier": "int",
    "name": "string",
    "code": "int",
    "planned_down": "int",
    "unplanned_down": "int",
}
