#!/bin/bash
set -e

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-01"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260501.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-02"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260502.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-03"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260503.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-04"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260504.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-05"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260505.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-06"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260506.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-07"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260507.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-08"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260508.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-09"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260509.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-10"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260510.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-11"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260511.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-12"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260512.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-13"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260513.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-14"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260514.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-15"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260515.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

# echo "Invoking Lambda function to transform THF raw events data from 2026-05-16"
# aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260516.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json

echo "Invoking Lambda function to transform THF raw events data from 2026-05-17"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260517.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-18"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260518.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-19"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260519.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-20"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260520.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-21"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260521.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-22"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260522.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-23"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260523.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-24"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260524.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-25"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260525.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-26"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260526.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-27"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260527.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-28"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260528.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-29"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260529.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-30"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260530.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1

echo "Invoking Lambda function to transform THF raw events data from 2026-05-31"
aws lambda invoke --function-name bax-bxty-thf-etl --region eu-central-1 --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{"save_to_s3": true, "events_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/raw/events/raw_events_20260531.jsonl", "part_configuration_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_part_configurations/part_configuration.parquet", "machine_status_code_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/dim_machines_status_code/machines_status_code.parquet", "s3_output_path": "s3://bax-bxty-thf-data-warehouse/warehouse/thf/curated/fact_events/"}' response.json >/dev/null 2>&1
