SCHEMAS = {
    "part_configuration": {
        "id": "int32",
        "seconds_per_part": "float64",
        "machine_id": "int32",
        "part_id": "int32",
        "conversion_cost": "float64",
        "material_cost": "float64",
        "seconds_per_part_2": "float64",
        "multiplier": "float64",
        "p_id": "int32",  # renombrado para evitar el punto
        "name": "string",
        "description": "string",
    },
    "machine_status_code": {
        "id": "int32",
        "code": "int32",
        "description": "string",
        "status_id": "int32",
        "level_2_related": "int32",
        "s_id": "int32",
        "name": "string",
        "running": "int8",
        "unplanned_down": "int8",
        "planned_down": "int8",
        "color": "string",
        "icon": "int32",
        "order": "int32",
        "application_issue": "int8",
        "color_set": "string",
    },
    "machines_groups_hierarchy": {
        "machine_group_child_id": "int64",
        "machine_group_child_name": "string",
        "machine_group_parent_id": "int64",
        "machine_group_parent_name": "string",
        "machine_group_grandparent_id": "int64",
        "machine_group_grandparent_name": "string",
        "machine_group_great_grandparent_id": "int64",
        "machine_group_great_grandparent_name": "string",
    },
    "shifts": {
        "id": "int",
        "name": "string",
        "color": "string",
        "is_active": "int",
        "active_start_date": "timestamp",
        "active_end_date": "timestamp",
        "group_id": "int",
        "erp_shift_name": "string",
    },
}
